### ISSUE TITLE
Error encountered: Assertion `cm.check()' failed

### ISSUE THREAD

**Issue by matthewsot** [bitwuzla/bitwuzla#51] opened 2023-07-01 19:18 UTC
Hello, and thanks for the great solver !

Per the release of 0.1.0, I've ported a project that was running fine with `yices` and `cvc5` to also support the new `bitwuzla`. Unfortunately, I'm hitting this error:
```
bitwuzla: ../src/solving_context.cpp:57: bzla::Result bzla::SolvingContext::solve(): Assertion `cm.check()' failed.
Aborted
```
I've used ddSMT (thanks for that too!) to reduce the triggering input to this:
```
(declare-const p (_ BitVec 1))
(declare-fun m () (Array (_ BitVec 1) (Array (_ BitVec 1) (_ BitVec 1))))
(assert (= (_ bv0 1) (ite (distinct (_ bv0 1) (select (select m (_ bv0 1)) (_ bv0 1))) (_ bv0 1) (_ bv1 1))))
(assert (= p (ite (distinct (_ bv0 1) (select (select (store m (_ bv0 1) (store (select m (_ bv0 1)) (_ bv0 1) (ite (= (_ bv0 1) (select (select (store m (_ bv0 1) (store (select m (_ bv0 1)) (_ bv0 1) (select (select (store m (_ bv0 1) (store (select m (_ bv0 1)) (_ bv0 1) (select (select (store m (_ bv0 1) (store (select m (_ bv0 1)) (_ bv0 1) (ite (= (_ bv0 1) (select (select m (_ bv0 1)) (_ bv0 1))) (_ bv1 1) (_ bv0 1)))) (select (select m (_ bv0 1)) (_ bv0 1))) (select (select m (_ bv0 1)) (_ bv0 1))))) (_ bv0 1)) (_ bv0 1)))) (_ bv0 1)) (_ bv0 1))) (_ bv1 1) (_ bv0 1)))) (_ bv0 1)) (_ bv0 1))) (_ bv1 1) (_ bv0 1))))
(assert (= (_ bv0 1) p))
(check-sat)
(get-model)
```

I have confirmed that (after prepending with a set-logic QF_ABV) this file is determined `sat` by Z3, CVC5, and Yices. I have built Bitwuzla from source on commit `5a0e2d7177272a1d483f1b4a1126b1f38fd01fb7`.

Any thoughts for avoiding this would be welcome.

**Comment by matthewsot** [comment] 2023-07-01 19:23
It "works" if I pass `--check-model=false`, so I guess there must be something wrong with the model.

**Comment by matthewsot** [comment] 2023-07-01 19:25
Here's the model it claims:
```
(
  (define-fun p () (_ BitVec 1) #b1)
  (define-fun m () (Array (_ BitVec 1) (Array (_ BitVec 1) (_ BitVec 1))) (let ((_let0 ((as const (Array (_ BitVec 1) (_ BitVec 1))) #b0))) (store (store ((as const (Array (_ BitVec 1) (Array (_ BitVec 1) (_ BitVec 1)))) _let0) #b0 (store _let0 #b0 #b1)) #b1 (store _let0 #b1 #b1))))
)
```
which cvc5 seems to agree is not an OK model.

**Comment by matthewsot** [comment] 2023-07-04 12:15
Further simplified:
```
(declare-const p Bool)
(declare-fun m () (Array Bool (Array Bool Bool)))

(define-fun m0 () (Array Bool Bool) (select m false))
(define-fun m00 () Bool (select m0 false))

(assert m00)
(assert (= p (not (select (select (store m false (store m0 false (not m00))) m00) m00))))
(assert (not p))
(check-sat)
```
I also find that it doesn't fail when I pass `--preprocess=false`, so perhaps something in the preprocessor isn't expecting multidim arrays?

I tried `-l=3` before & after moving the `(assert (not p))` above the second assertion (when it is above the second assertion, it works). The main difference seems to be that it immediately substitutes `Add substitution: p -> false`, while the buggy version does `Add substitution: p -> (!@t11 (not @t10))`

**Comment by matthewsot** [comment] 2023-07-04 13:41
OK, here's the most simplified I've been able to get:
```
(declare-const p Bool)
(declare-fun m () (Array Bool (Array Bool Bool)))
(define-fun m0 () (Array Bool Bool) (select m false))
(define-fun m00 () Bool (select m0 false))

(assert m00)
(assert (= p (not (select (select (store m false (store m0 false false)) m00) true))))
(assert (not p))
(check-sat)
```
The (correct) model for `m` looks like `[[T,F], [F,T]]`.

I've also attached a log (with some extra logging output that I added; sorry if it complicates reading):
[bad.log](https://github.com/bitwuzla/bitwuzla/files/11949793/bad.log)

As far as I can tell, the issue seems to be occurring somewhere in `ArraySolver::get_index_value_pairs`. When it is called for the index-value pairs of `(!@t13 (select @t12 @t5))`, it just returns a default (all-false) array. I think `@t13` corresponds to the term:
```
(select (store m false (store m0 false false)) m00)
```
which should be `[F, T]`, not `[F, F]`, because `m00 = T` and `m = [[T, F], [F, T]]`.

**Comment by matthewsot** [comment] 2023-07-04 15:39
See https://github.com/matthewsot/bitwuzla/commit/4abc05e943133dc5f5360a53ff6568a1957f7025

**Comment by mpreiner** [comment] 2023-07-04 20:58
Thanks for the bug report! I already have an idea what the issue is and this should be fixed soon.

**Comment by matthewsot** [comment] 2023-07-05 04:03
Awesome, thanks!

**Closed** 2023-07-06 09:04 UTC
