### ISSUE TITLE
Build issue on MacOS with clang++ 16.0.6

### ISSUE THREAD

**Issue by gussmith23** [bitwuzla/bitwuzla#67] opened 2023-09-12 16:07 UTC
```
[39/66] Compiling C++ object src/libbitwuzla.a.p/solver_bv_bv_prop_solver.cpp.o
FAILED: src/libbitwuzla.a.p/solver_bv_bv_prop_solver.cpp.o 
c++ -Isrc/libbitwuzla.a.p -Isrc -I../src -I../include -Isrc/lib -I../src/lib -Isubprojects/symfpu -I../subprojects/symfpu -Isubprojects/cadical-rel-1.5.2/src -I../subprojects/cadical-rel-1.5.2/src -Isubprojects/symfpu/symfpu/core -Isubprojects/symfpu/symfpu/utils -I/usr/local/Cellar/gmp/6.2.1_1/include -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -O3 -MD -MQ src/libbitwuzla.a.p/solver_bv_bv_prop_solver.cpp.o -MF src/libbitwuzla.a.p/solver_bv_bv_prop_solver.cpp.o.d -o src/libbitwuzla.a.p/solver_bv_bv_prop_solver.cpp.o -c ../src/solver/bv/bv_prop_solver.cpp
../src/solver/bv/bv_prop_solver.cpp:278:21: error: conditional expression is ambiguous; 'std::__1::optional<std::__1::reference_wrapper<const std::__1::basic_string<char> > >::value_type' (aka 'std::__1::reference_wrapper<const std::__1::basic_string<char> >') can be converted to 'basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >' and vice versa
      node.symbol() ? *node.symbol() : "@t" + std::to_string(node.id());
                    ^ ~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

clang++ verison:
```
Homebrew clang version 16.0.6
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/16.0.6/bin
```

I can fix it with this patch:

```diff
diff --git a/src/solver/bv/bv_prop_solver.cpp b/src/solver/bv/bv_prop_solver.cpp
index 64d189d3..78004136 100644
--- a/src/solver/bv/bv_prop_solver.cpp
+++ b/src/solver/bv/bv_prop_solver.cpp
@@ -275,7 +275,7 @@ BvPropSolver::mk_node(const Node& node)
   }
 
   std::string symbol =
-      node.symbol() ? *node.symbol() : "@t" + std::to_string(node.id());
+      node.symbol() ? (*node.symbol()).get() : "@t" + std::to_string(node.id());
 
   switch (node.kind())
   {
```

**Comment by mpreiner** [comment] 2023-09-12 19:33
Fixed on main, interestingly, I could not reproduce this on
```
% clang++ --version
Homebrew clang version 16.0.6
Target: arm64-apple-darwin21.6.0
Thread model: posix
```

**Closed** 2023-09-12 19:32 UTC

**Comment by gussmith23** [comment] 2023-09-12 20:50
That's really strange. Thank you though!!
