### ISSUE TITLE
Compile errors from bitwuzla-bin package in opam-repository.

### ISSUE THREAD

**Issue by tmcgilchrist** [bitwuzla/bitwuzla#68] opened 2023-09-14 04:00 UTC
The following compile errors / warnings are generated in the opam repository CI for this package. 
Platform Debian 12 x86_64 with OCaml 4.14 and 5.0. 

```
# g++ -Wall -Wextra -O3 -DNDEBUG -fPIC -I../build -c ../src/reap.cpp
# make[1]: Leaving directory '/home/opam/.opam/5.0/.opam-switch/build/bitwuzla-bin.0.0.0/_build/default/vendor/cadical/build'
# In file included from ../src/lookahead.cpp:1:
# In constructor 'CaDiCaL::CubesWithStatus::CubesWithStatus(CaDiCaL::CubesWithStatus&&)',
#     inlined from 'CaDiCaL::CubesWithStatus CaDiCaL::Internal::generate_cubes(int, int)' at ../src/lookahead.cpp:391:12:
# ../src/internal.hpp:100:8: warning: 'cubes.CaDiCaL::CubesWithStatus::status' may be used uninitialized [-Wmaybe-uninitialized]
#   100 | struct CubesWithStatus {
#       |        ^~~~~~~~~~~~~~~
# ../src/lookahead.cpp: In member function 'CaDiCaL::CubesWithStatus CaDiCaL::Internal::generate_cubes(int, int)':
# ../src/lookahead.cpp:389:21: note: 'cubes' declared here
#   389 |     CubesWithStatus cubes;
#       |                     ^~~~~
# In file included from ../src/reap.cpp:1:
# ../src/reap.hpp:15:10: error: 'size_t' does not name a type
#    15 |   inline size_t size() {
#       |          ^~~~~~
# ../src/reap.hpp:5:1: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
#     4 | #include <vector>
#   +++ |+#include <cstddef>
#     5 | 
# ../src/reap.hpp:23:3: error: 'size_t' does not name a type
#    23 |   size_t num_elements;
#       |   ^~~~~~
# ../src/reap.hpp:23:3: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
# ../src/reap.hpp: In member function 'bool Reap::empty()':
# ../src/reap.hpp:12:13: error: 'num_elements' was not declared in this scope
#    12 |     return !num_elements;
#       |             ^~~~~~~~~~~~
# ../src/reap.cpp: In member function 'void Reap::release()':
# ../src/reap.cpp:16:3: error: 'num_elements' was not declared in this scope
#    16 |   num_elements = 0;
#       |   ^~~~~~~~~~~~
# ../src/reap.cpp: In constructor 'Reap::Reap()':
# ../src/reap.cpp:23:3: error: 'num_elements' was not declared in this scope
#    23 |   num_elements = 0;
#       |   ^~~~~~~~~~~~
# ../src/reap.cpp: In member function 'void Reap::push(unsigned int)':
# ../src/reap.cpp:45:3: error: 'num_elements' was not declared in this scope
#    45 |   num_elements++;
#       |   ^~~~~~~~~~~~
# ../src/reap.cpp: In member function 'unsigned int Reap::pop()':
# ../src/reap.cpp:113:7: error: 'num_elements' was not declared in this scope
#   113 |     --num_elements;
#       |       ^~~~~~~~~~~~
# ../src/reap.cpp: In member function 'void Reap::clear()':
# ../src/reap.cpp:126:3: error: 'num_elements' was not declared in this scope
#   126 |   num_elements = 0;
#       |   ^~~~~~~~~~~~
# make[1]: *** [makefile:34: reap.o] Error 1
# make: *** [makefile:3: all] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build bitwuzla-bin 0.0.0
+- 
+- The following changes have been performed
| - install conf-cmake 1
| - install conf-g++   1.0
| - install conf-git   1.1
| - install conf-gmp   4
| - install dune       3.10.0
+- 
# Run eval $(opam env) to update the current shell environment

The former state can be restored with:
    /usr/bin/opam switch import "/home/opam/.opam/5.0/.opam-switch/backup/state-20230914011238.export"
[WARNING] OPAMCONFIRMLEVEL was ignored because CLI 2.0 was requested and it was introduced in 2.1.
[WARNING] OPAMCONFIRMLEVEL was ignored because CLI 2.0 was requested and it was introduced in 2.1.
"/usr/bin/env" "bash" "-c" "opam reinstall bitwuzla-bin.0.0.0;
        res=$?;
        test "$res" != 31 && exit "$res";
        export OPAMCLI=2.0;
        build_dir=$(opam var prefix)/.opam-switch/build;
        failed=$(ls "$build_dir");
        partial_fails="";
        for pkg in $failed; do
          if opam show -f x-ci-accept-failures: "$pkg" | grep -qF "\"debian-12\""; then
            echo "A package failed and has been disabled for CI using the 'x-ci-accept-failures' field.";
          fi;
          test "$pkg" != 'bitwuzla-bin.0.0.0' && partial_fails="$partial_fails $pkg";
        done;
        test "${partial_fails}" != "" && echo "opam-repo-ci detected dependencies failing: ${partial_fails}";
        exit 1" failed with exit status 1
2023-09-14 01:14.55: Job failed: Failed: Build failed
2023-09-14 01:14.55: Log analysis:
2023-09-14 01:14.55: >>> 
[ERROR] The compilation of bitwuzla-bin.0.0.0 failed at "dune build -p bitwuzla-bin -j 47 @install".
 (score = 20)
2023-09-14 01:14.55: >>> 
# ../src/reap.hpp:15:10: error: 'size_t' does not name a type
 (score = 30)
2023-09-14 01:14.55: >>> 
# ../src/reap.hpp:23:3: error: 'size_t' does not name a type
 (score = 30)
2023-09-14 01:14.55: >>> 
# ../src/reap.hpp:12:13: error: 'num_elements' was not declared in this scope
 (score = 30)
2023-09-14 01:14.55: >>> 
# ../src/reap.cpp:16:3: error: 'num_elements' was not declared in this scope
 (score = 30)
2023-09-14 01:14.55: >>> 
# ../src/reap.cpp:23:3: error: 'num_elements' was not declared in this scope
 (score = 30)
2023-09-14 01:14.55: >>> 
# ../src/reap.cpp:45:3: error: 'num_elements' was not declared in this scope
 (score = 30)
2023-09-14 01:14.55: >>> 
# ../src/reap.cpp:113:7: error: 'num_elements' was not declared in this scope
 (score = 30)
2023-09-14 01:14.55: >>> 
# ../src/reap.cpp:126:3: error: 'num_elements' was not declared in this scope
 (score = 30)
2023-09-14 01:14.55: 'size_t' does not name a type
```

Full logs available at https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/e4ab39cf1252709989554bf19c88b572a43bf624.

**Comment by mpreiner** [comment] 2023-09-14 20:07
This looks more like a compilation issue of [CaDiCaL](https://github.com/arminbiere/cadical). Can you try to compile CaDiCaL standalone on your system and see if you have the same issue?

**Comment by recoules** [comment] 2023-09-14 21:08
It is just the Opam CI trying to compile a very old version of bitwuzla/CaDiCal (> 2 years) with newest version of GCC. I made a request to mark the package deprecated (https://github.com/ocaml/opam-repository/pull/24442).

**Comment by mpreiner** [comment] 2023-09-14 23:14
Hmm, what's also a bit weird now is that in opam there are 1.0.* releases of Bitwuzla, but there was never an official 1.0.0 release. Once we get there, there'll potentially be issues with conflicting versions? Is there a way to fix this?

**Comment by recoules** [comment] 2023-09-20 07:33
Well, `bitwuzla` package (version `1.0.5`) is the OCaml "*high*" level API (for now discontinued) while `bitwuzla-c` is the one to one C binding (deprecated) and `bitwuzla-cxx` the one to one C++ binding (currently following the main bitwuzla versioning).
The `bitwuzla` package may evolve in a future at a different speed than the main project because it does not have the same exposed features.

**Comment by mpreiner** [comment] 2023-09-22 18:39
Alright, let's cross that bridge when we get there. @tmcgilchrist I assume the issue is now fixed in the opam repository? If not, feel free to reopen the issue.

**Closed by mpreiner** 2023-09-22 18:39 UTC
